# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Powder to the People
tagline:          'Whatever your powder is...'
description:      'Javscript, CSS & Beer'
url:              http://www.powdertothepeople.tv
baseurl:          /

author:
  name:           'Sten Muchow'
  url:            https://twitter.com/powdertothepeople

paginate:         5

# Custom vars

gems: [jekyll-paginate]