# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false

# Permalinks
permalink: pretty

# Setup
title: Powder to the People
tagline: "Whatever your powder is..."
description: "Frontend Fun!"
url: https://www.powdertothepeople.tv
baseurl: /

author:
    name: "Sten Muchow"
    url: https://twitter.com/powdertothepeople

paginate: 5

# Custom vars

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
